### ISSUE TITLE
[idea] track loose and wins

### ISSUE THREAD

**Issue by nerdalertdk** [BAROD/Koth-Kavala#9]
Would be cool to track how many times a player have lost or won a round

**Comment by Angrygargamel** [comment]
i would say you have to check then if the player has played the whole round or if he connected shortly before the round ended...
should be some minimum percentage be played of the round to get counted for this...

**Comment by nerdalertdk** [comment]
Yeah maybe just make it team based? So total blu, green and red wins ?

**Comment by nerdalertdk** [comment]
Easy way to track players game time, set an variable with join time, then if the player have been on the server for 30 min, he gets an Win if there team wins ?

I can make a lightweight PHP site to display stats.
